vrsion: '3'

services:
  database:
    container_name: NCHC_mysql
    image: mysql:8.0
    restart: unless-stopped
    logging:
      driver: "json-file"
    volumes:
      - ./vol/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<Mysql password>
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=<Codimd password>
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Taipei
    ports:
      - "3306:3306"
  grafana:
    container_name: NCHC_grafana
    image: grafana/grafana:7.1.5
    restart: unless-stopped
    user: "472"
    logging:
      driver: "json-file"
    volumes:
      - ./vol/grafana:/var/lib/grafana
    environment:
      TZ: Asia/Taipei
    ports:
      - "10303:3000"
  swagger-ui:
    container_name: NCHC_swagger
    image: swaggerapi/swagger-ui:v3.32.5
    restart: unless-stopped
    logging:
      driver: "json-file"
    environment:
      TZ: Asia/Taipei
    ports:
      - "10302:8080"
  jupyter:
    container_name: NCHC_jupyterlab
    image: jupyter-dev:latest
    build:
      context: ./jupyter-dev
      dockerfile: ${PWD}/jupyter-dev/Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
    volumes:
      - ./vol/jupyter:/home/jovyan/NCHC
    environment:
      TZ: Asia/Taipei
    ports:
      - "10301:8888"
  gitlab:
    container_name: NCHC_gitlab
    image: gitlab/gitlab-ee
    restart: unless-stopped
    logging:
      driver: "json-file"
    hostname: "{host-ip}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://{host-ip}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2323
      TZ: Asia/Taipei
    ports:
      - "443:443"
      - "80:80"
      - "2323:22"
    volumes:
      - ./vol/gitlab/config:/etc/gitlab
      - ./vol/gitlab/logs:/var/log/gitlab
      - ./vol/gitlab/data:/var/opt/gitlab
  codimd:
    image: nabo.codimd.dev/hackmdio/hackmd:2.2.0
    container_name: NCHC_codimd
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - CMD_DB_URL=mysql://codimd:<Codimd password>@database/codimd
      - PGID=1000
      - PUID=1000
      - TZ=Asia/Taipei
    ports:
      - "3000:3000"
  jenkins:
    container_name: NCHC_jenkins
    image: jenkins/jenkins:2.249.3-lts-centos7
    restart: unless-stopped
    volumes:
      - ./vol/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
  swagger-editor:
    container_name: NCHC_swagger_editor
    image: swaggerapi/swagger-editor
    restart: unless-stopped
    ports:
      - "10304:8080"
